services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://app:app@db:5432/app"
      MCP_API_TOKEN: "dev-token"
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
