services:
  app:
    build: .
    environment:
      PORT: "8080"
      MCP_API_TOKEN: "dev-token"
    ports: ["8080:8080"]
    volumes:
      - sqlite_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
